### ISSUE TITLE
Share on Instagram is not working. I am passing object with byte code of data and some static caption info. below is output when I run $cordovaInstagram.share($scope.image.data, $scope.image.caption).then(function() {}, function(err) { });

### ISSUE THREAD

**Issue by darpanvithani** [driftyco/ng-cordova#1325]
TypeError: Cannot read property 'slice' of undefined
    at Object.Plugin.share (http://192.168.51.2:8100/plugins/cordova-instagram-plugin/www/CDVInstagramPlugin.js:93:18)
    at Object.share (http://192.168.51.2:8100/lib/ngCordova/dist/ng-cordova.js:4653:17)
    at Scope.$scope.shareViaInstagram (http://192.168.51.2:8100/js/controllers.js:703:23)
    at fn (eval at <anonymous> (http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:27638:15), <anonymous>:4:242)
    at http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:65427:9
    at Scope.$eval (http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:30395:28)
    at Scope.$apply (http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:30495:25)
    at HTMLAnchorElement.<anonymous> (http://192.168.51.2:8100/lib/ionic/js/ionic.bundle.js:65426:13)
    at HTMLAnchorElement.n.event.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js:3:7537)
    at HTMLAnchorElement.r.handle (https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js:3:5620)

**Comment by mpk2** [comment]
The documentation for this method is wrong. If you look at the source of the share method

```
share: function (options) {
      var q = $q.defer();

      if (!window.Instagram) {
        console.error('Tried to call Instagram.share but the Instagram plugin isn\'t installed!');
        q.resolve(null);
        return q.promise;
      }

      Instagram.share(options.image, options.caption, function (err) {
        if(err) {
          q.reject(err);
        } else {
          q.resolve(true);
        }
      });
      return q.promise;
    }
```

The share method requires one object with two properties instead of two separate arguments
