### ISSUE TITLE
Getting error after connected with social network (fb and google_plus) on WP8

### ISSUE THREAD

**Issue by visnupriya** [driftyco/ng-cordova#578]
I am getting error as shown below after login with fb or gplus social network. Please help. How to resolve that issue. It is getting on WP8 device only same code works fine on Android and iPhone

```javascript
ERROR:TypeError: Unable to get property 'addEventListener' of undefined or null reference
   at google (x-wmapp0:www/js/ng-cordova.js:2829:11)
   at $scope.connectToGP (x-wmapp0:www/js/controllers.js:426:5)
   at Anonymous function (x-wmapp0:www/js/angular.min.js:177:56)
   at Anonymous function (x-wmapp0:www/js/angular-touch.js:419:9)
   at k.prototype.$eval (x-wmapp0:www/js/angular.min.js:112:57)
   at k.prototype.$apply (x-wmapp0:www/js/angular.min.js:112:322)
   at Anonymous function (x-wmapp0:www/js/angular-touch.js:418:7)
   at b.event.dispatch (x-wmapp0:www/js/lib/jquery.min.js:3:28281)
   at v.handle (x-wmapp0:www/js/lib/jquery.min.js:3:24972)
CordovaBrowser_LoadCompleted
A first chance exception of type 'System.SystemException' occurred in Microsoft.Phone.Interop.ni.dll
Error calling js to fire nativeReady event. Did you include cordova.js in your html script tag?

CordovaBrowser_NavigationFailed :: https://accounts.google.com/o/oauth2/approval?hd=gmail.com&as=3fxxxxxx85797c2e&hl=en_GB&pageId=none&xsrfsign=APsBzxxxxxxAVL0BVElnqr8hP67xxxxxxxxxxTzSrVPG

**Comment by pbernasconi** [comment]
Can you share some code that you're working with. Also what plugin are you using? It seems you might be using the $cordovaOAuth plugin, you might need to check if it works on WP8.

**Comment by visnupriya** [comment]
I tried as shown below for google_plus 
```javascript
$cordovaOauth.google("Google-CLIENT ID", ["https://www.googleapis.com/auth/plus.login"]).then(function(result) {
      console.log(result);
      console.log(result.access_token);
      var gp_access_token = result.access_token;
      $http.get("https://www.googleapis.com/plus/v1/people/me", { params: { access_token: gp_access_token, fields: "id,displayName", format: "json" }}).then(function(result) {
        $scope.profileData = result.data;
        console.log(result);
        console.log("----" + result.data.id);

      }, function(error) {
        alert("There was a problem getting your profile.  Check the logs for details.");
        console.log(error);
      });
    }, function(error) {
      console.log(error)
    })

**Comment by visnupriya** [comment]
Any help?

**Comment by nraboy** [comment]
You opened the same ticket in my repository as well:

https://github.com/nraboy/ng-cordova-oauth/issues/25

With that said, I think this ticket should be closed due to it being a WP8 compatibility problem.  Ionic only officially supports iOS and Android.

Regards,

**Comment by visnupriya** [comment]
Yes I know but I am using AngularJS with my cordova application.

**Comment by nraboy** [comment]
What is on line 426 of controller.js as mentioned here:

```
at $scope.connectToGP (x-wmapp0:www/js/controllers.js:426:5)
```

Are you using Ionic Framework or vanilla Apache Cordova?  

The errors listed really don't indicate any problems with the Oauth library.  The library essentially just opens and closes a web browser.  Not much to it.

Like I said in the comment of my Git repository, `x-wmapp0` leads me to believe you have not built a binary file.  I'm not too familiar with WP8, but that looks kind of like a local server.

**Comment by ajeesh13** [comment]
@visnupriya I have the same problem with corodova-oauth while using fb and g+ login.

In fb it behaved like First login click fails even though I have entered the correct user name and password.For the second login click means I didn't change any value in user name and password the pop up will turned into facebook.There I can see my posts and all other stuff.My ionic app will be remain in back of the pop-up window.

Have you got any solution for this issue?
If you have found any solution please share the sample code

Thanks in advance
Ajeesh
