### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by nvcken** [driftyco/ng-cordova#582]
```
bower invalid-meta  ngCordova is missing "main" entry in bower.json
bower invalid-meta  ngCordova is missing "ignore" entry in bower.json
bower EPERM         EPERM, unlink 'C:\Users\Ken\AppData\Local\Temp\my-lap-Ken\bower\n
gCordova-7276-xURwu8\archive.tar.gz'

Stack trace:
Error: EPERM, unlink 'C:\Users\Ken\AppData\Local\Temp\my-lap-Ken\bower\ngCordova-7276
-xURwu8\archive.tar.gz'

Console trace:
Trace
    at StandardRenderer.error (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\lib\ren
derers\StandardRenderer.js:82:17)
    at Logger.<anonymous> (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\bin\bower:1
10:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\bower
-logger\lib\Logger.js:29:39)
    at C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:40:20
    at _rejected (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:
797:24)
    at C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:823:30
    at Promise.when (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.
js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\Ken\AppData\Roaming\npm\node_modules\bowe
r\node_modules\q\q.js:741:41)
    at C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Windows_NT 6.2.9200 ia32
```

**Comment by pbernasconi** [comment]
That's a strange error, and really should not be occuring. If you look at ngCordova's [bower file](https://github.com/driftyco/ng-cordova/blob/master/bower.json#L11-L12), you'll notice that the `main` and `ignore` are both in there.

I'll look into this.

**Comment by nvcken** [comment]
I think this is maybe my Ethernet problem while installing ngCordova, It's cause callback or streaming problem.
