### ISSUE TITLE
$cordovaGoogleAnalytics: Cannot call method 'trackView' of undefined 

### ISSUE THREAD

**Issue by ocomsoft** [driftyco/ng-cordova#625]
I am getting the following error when the App is started
```
TypeError: Cannot call method 'trackView' of undefined
    at Object.trackView (file:///android_asset/www/lib/ngCordova/dist/ng-cordova.js:2752:27)
    at file:///android_asset/www/js/app.js:26:28
    at Scope.$broadcast (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20605:28)
    at $state.transition.resolved.then.$state.transition (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:34122:22)
    at wrappedCallback (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19197:81)
    at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:19283:26
    at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20326:28)
    at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20138:31)
    at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20430:24)
    at done (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:16003:45) 
```

On my Samsung Galaxy S5 - Using Android 4.4.2

I have the following code in my Ionic (1.0.0-beta.13) Project using ngCordova (0.1.12-alpha)

````
angular.module('starter', ['ionic', 'starter.controllers'])

.run(function($ionicPlatform, $rootScope, $cordovaGoogleAnalytics) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
    
    $cordovaGoogleAnalytics.startTrackerWithId('UA-XXXXXXX-XX');   
  });
  
  $rootScope.$on('$stateChangeSuccess', 
		  function(event, toState, toParams, fromState, fromParams){
	  $cordovaGoogleAnalytics.trackView(toState.name);
  });
})
```

Seems the $window.analytics is undefined and the code is not checking.  I tried an upgrade to Ionic 1.0.0-beta.14 and the problem persists.

**Comment by cnd5041** [comment]
Do you have to include ngCordova in the module?
angular.module('starter', ['ionic', 'ngCordova', 'starter.controllers'])

**Comment by ocomsoft** [comment]
Sorry. Looks like you are right.. I had added the module to another module but not in the app module.
