### ISSUE TITLE
Email Composer plugin not installing properly.

### ISSUE THREAD

**Issue by wootwoot1234** [driftyco/ng-cordova#660]
I ran this:

    cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git@0.8.2

and got an error:

    Fetching plugin "https://github.com/katzer/cordova-plugin-email-composer.git@0.8.2" via git clone
    Error: Command failed: Cloning into '/var/folders/c0/314w0cp10g91pvkzf8v57zlr0000gn/T/plugman/git/1425242705416'...
    fatal: unable to access 'https://github.com/katzer/cordova-plugin-email-composer.git@0.8.2/': The requested URL returned error: 400

        at ChildProcess.exithandler (child_process.js:648:15)
        at ChildProcess.emit (events.js:98:17)
        at maybeClose (child_process.js:756:16)
        at Socket.<anonymous> (child_process.js:969:11)
        at Socket.emit (events.js:95:17)
        at Pipe.close (net.js:465:12)

Looks like katzer just made some changes, as of right now there was a commit 6 hours ago.

**Comment by wootwoot1234** [comment]
From katzer, looks like the docs have a typo.

It's

    cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2

or

    cordova plugin add de.appplant.cordova.plugin.email-composer@0.8.2
