### ISSUE TITLE
 ReferenceError: facebookConnectPlugin is not defined

### ISSUE THREAD

**Issue by nur858** [driftyco/ng-cordova#892]
I know this has been reported before and i have tried almost all the solutions i found but none worked for me. what am i doing wrong?

 ReferenceError: facebookConnectPlugin is not defined
    at Object.login (file:///android_asset/www/lib/js/bower_components/ngCordova/dist/ng-cordova.js:1605:11)
    at new <anonymous> (file:///android_asset/www/js/app.js:46:24)
    at Object.invoke (file:///android_asset/www/lib/js/bower_components/angular/angular.js:4450:17)
    at extend.instance (file:///android_asset/www/lib/js/bower_components/angular/angular.js:8999:34)
    at nodeLinkFn (file:///android_asset/www/lib/js/bower_components/angular/angular.js:8109:36)
    at compositeLinkFn (file:///android_asset/www/lib/js/bower_components/angular/angular.js:7541:13)
    at compositeLinkFn (file:///android_asset/www/lib/js/bower_components/angular/angular.js:7545:13)
    at publicLinkFn (file:///android_asset/www/lib/js/bower_components/angular/angular.js:7416:30)
    at file:///android_asset/www/lib/js/bower_components/angular/angular.js:1635:27
    at Scope.$eval (file:///android_asset/www/lib/js/bower_components/angular/angular.js:15846:28)

**Comment by gortok** [comment]
Can you share a minimal reproduction of this issue ? The code necessary for me to reproduce it?

**Comment by Ionitron** [comment]
Greetings @nur858!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
