### ISSUE TITLE
Dead link in $cordovaFile documentation

### ISSUE THREAD

**Issue by BetaBugish** [driftyco/ng-cordova#896]
It appears the cordova install line is broken.

When invoking:
```
cordova plugin add cordova-plugin-file
```

```
Fetching plugin "cordova-plugin-file" via plugin registry
Error: 404 Not Found: cordova-plugin-file
    at RegClient.<anonymous> (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
    at Request._callback (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
    at Request.self.callback (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:236:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

Cordova version:
```
[vincent@localhost ~]$ cordova -v
5.1.1
```

**Comment by root-io** [comment]
Update cordova to version 5

**Comment by BetaBugish** [comment]
I'm at 5.1.1.
```
[vincent@localhost ~]$ cordova -v
5.1.1
```

**Comment by root-io** [comment]
Hum, that's weird, there is no mistake with the command line.
https://github.com/apache/cordova-plugin-file#installation
Try `npm update -g`maybe ?

**Comment by BetaBugish** [comment]
This was completely my own fault, I never realized I was staring at strider output rather than my own terminal when compiling.

My bad.
