### ISSUE TITLE
EXDEV, Error clone repository pushplugin

### ISSUE THREAD

**Issue by devtosystems** [driftyco/ng-cordova#943]
Hello guys!

I do not running pushNotification plugin of the ionic tutorial. ;(
The error log appears below.
Should they need more information, please do not forget to ask.

```bash
$ cordova plugin add https://github.com/phonegap-build/PushPlugin.git
Fetching plugin "https://github.com/phonegap-build/PushPlugin.git" via git clone
Repository "https://github.com/phonegap-build/PushPlugin.git" checked out to git ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted '/tmp/git/1439840584782/Example'
    at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:77:8
    at Array.forEach (native)
    at Object._mv (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/mv.js:53:11)
    at Object.mv (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/shelljs/src/common.js:186:23)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:53:19
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/q/q.js:749:13)
```

The tutorial I push then you need the cord push the plugin is as follows:
http://docs.ionic.io/v1.0/docs/push-from-scratch

Clicking on the button "push" in the browser displays the error below:

```
TypeError: Cannot read property 'pushNotification' of undefined
    at Object.register (http://172.16.200.210:8101/lib/ngCordova/dist/ng-cordova.js:5701:24)
    at init (http://172.16.200.210:8101/lib/ionic-service-push/ionic-push.js:146:20)
    at http://172.16.200.210:8101/lib/ionic-service-push/ionic-push.js:309:21
    at new Q (http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:23650:5)
    at Q (http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:23637:14)
    at Object.register (http://172.16.200.210:8101/lib/ionic-service-push/ionic-push.js:270:14)
    at Scope.$scope.identifyUser.$scope.pushRegister (http://172.16.200.210:8101/js/controllers.js:36:28)
    at fn (eval at <anonymous> (http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:21972:15), <anonymous>:4:227)
    at http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:57514:9
    at Scope.$get.Scope.$eval (http://172.16.200.210:8101/lib/ionic/js/ionic.bundle.js:24673:28)(anonymous function) @ ionic.bundle.js:21157$get @ ionic.bundle.js:17936$get.Scope.$apply @ ionic.bundle.js:24774(anonymous function) @ ionic.bundle.js:57513eventHandler @ ionic.bundle.js:12098triggerMouseEvent @ ionic.bundle.js:2865tapClick @ ionic.bundle.js:2854tapMouseUp @ ionic.bundle.js:2927
```

Please, help me!
Thank you!

**Comment by Ionitron** [comment]
Greetings @devtosystems!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
