### ISSUE TITLE
Backgound Geolocation plugin

### ISSUE THREAD

**Issue by ygModesto** [driftyco/ng-cordova#961]
The Backgound Geolocation github plugin is moved and it's a premium version.
A legacy version url : https://github.com/christocracy/cordova-plugin-background-geolocation/tree/0.3.7

**Comment by jbielick** [comment]
+1 - the new repo code doesn't seem to mount `backgroundGeoLocation` to `$window.plugins` and cannot be used as expected / documented. Installing `#0.3.7` doesn't seem to work either:

```
> cordova plugin add 'git@github.com:christocracy/cordova-plugin-background-geolocation.git#0.3.7'
Fetching plugin "git@github.com:christocracy/cordova-plugin-background-geolocation.git" via npm
Fetching from npm failed: No compatible version found: git@'github.com:christocracy/cordova-plugin-background-geolocation.git'
Valid install targets:
["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
Error: No compatible version found: git@'github.com:christocracy/cordova-plugin-background-geolocation.git'
Valid install targets:
["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
    at installTargetsError (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:719:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/lib/cache.js:638:10
    at RegClient.get_ (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:105:14)
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:41:12)
    at fs.js:334:14
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by Ionitron** [comment]
Greetings @ygModesto!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
